#!/bin/sh
# vim filetype=sh

ARGSFILE="harnessArgs"

echo before add $(wc -l $ARGSFILE)

for i in $(seq 0 0.1 1);do
      for j in $(seq 0 0.1 1);do
            echo $i $j >> $ARGSFILE
      done
done

echo after add $(wc -l $ARGSFILE)
